apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx:1.23.3
    imagePullPolicy: IfNotPresent
  nodeSelector:
    disktype: ssd
