apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
      app: redis
spec:
  containers:
  - name: redis
    image: redis:7.0.10
    args: ["--requirepass", "$(REDIS_PASS)"]
    env:
      - name: REDIS_PASS
        valueFrom:
          secretKeyRef:
            name: redis
            key: password
